### ISSUE TITLE
Not working with ng v13

### ISSUE THREAD

**Issue by ajuni880** [chihab/ngx-env#6]
Hi, 

I have installed(`ng add @ngx-env/builder`) this dependency in an angular project with version: `13.0.0` and when I try to serve it fails. I get the next error

`
[error] TypeError: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.
    at getBrowserConfig (/mypath/node_modules/@angular-devkit/build-angular/src/webpack/configs/browser.js:18:21)
    at /mypath/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js:127:44
    at /mypath/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:72:16
    at generateWebpackConfig (/mypath/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:61:40)
    at async generateBrowserWebpackConfigFromContext (/mypath/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:123:20)
    at async generateI18nBrowserWebpackConfigFromContext (/mypath/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:70:20)
    at async setup (/mypath/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js:124:47)
`

Thanks

**Comment by chihab** [comment]
Hi @ajuni880, thanks for reporting the issue.

**Comment by chihab** [comment]
It seems like ngx-build-plus has the same issue https://github.com/manfredsteyer/ngx-build-plus/issues/307

**Comment by chihab** [comment]
Could you please check again?
Please update the @ngx-env/builder package to 2.0.0.

**Comment by ajuni880** [comment]
@chihab it works! thanks for the quick fix
